<?php

namespace AssuranceBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function CheckLogin($user,$pwd){
        $qb=$this->getEntityManager()
            ->createQuery("SELECT COUNT (u) as nb 
                            FROM AssuranceBundle:User u
                            WHERE u.username='$user' AND u.password='$pwd'");


        return $qb->getResult();
    }
    public function getuserbyauusrance($user,$pwd){
        $qb=$this->getEntityManager()
            ->createQuery("SELECT u 
                            FROM AssuranceBundle:User u
                            WHERE u.username='$user' AND u.password='$pwd'");


        return $qb->getResult();
    }





}