<?php

namespace EntityBundle\Repository;

/**
 * constatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class constatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByIDclient($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.ID_client='$id' ORDER BY m.dateConstat DESC");
        return $query->getResult();
    }
    public function findByIDclientEtat($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.ID_client='$id' ORDER BY m.etat DESC");
        return $query->getResult();
    }
    public function findByIDRefused($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.ID_client='$id' AND m.etat = -1 ORDER BY m.dateConstat DESC ");
        return $query->getResult();
    }
    public function findByIDNotyet($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.ID_client='$id' AND m.etat = 0 ORDER BY m.dateConstat DESC ");
        return $query->getResult();
    }
    public function findByIDloading($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.ID_client='$id' AND m.etat = 1 ORDER BY m.dateConstat DESC ");
        return $query->getResult();
    }
    public function findByIDDone($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.ID_client='$id' AND m.etat = 2 ORDER BY m.dateConstat DESC ");
        return $query->getResult();
    }
    public function findByDone()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.etat = 2 ORDER BY m.dateConstat DESC ");
        return $query->getResult();
    }
    public function findByRefused()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.etat = -1 ORDER BY m.dateConstat DESC ");
        return $query->getResult();
    }
    public function findByNotyet()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.etat = 0 ORDER BY m.dateConstat DESC ");
        return $query->getResult();
    }
    public function findByloading()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT m from EntityBundle:constat m WHERE m.etat = 1 ORDER BY m.dateConstat DESC ");
        return $query->getResult();
    }
}
