<?php

namespace EntityBundle\Repository;

/**
 * faqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faqRepository extends \Doctrine\ORM\EntityRepository
{
}
