<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;

/**
 * notificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getnotif($receiver){
        $query = $this->getEntityManager()
            ->createQuery("select count(n.id) from EntityBundle:notification n WHERE n.receiver=:id")
            ->setParameter('id',$receiver);

        try {
            return $query->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
        }

    }
}
