<?php

namespace EntityBundle\Repository;

/**
 * reclamation_externeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamation_externeRepository extends \Doctrine\ORM\EntityRepository
{
}
