<?php

namespace EntityBundle\Repository;

/**
 * reclamation_interneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamation_interneRepository extends \Doctrine\ORM\EntityRepository
{
}
