<?php

namespace EntityBundle\Repository;

/**
 * voituresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voituresRepository extends \Doctrine\ORM\EntityRepository
{
}
